name: CD workflow

on:
  pull_request:
    types: [ closed ]
    branches:
      - main
jobs:
  deploy:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: act10ns/slack@v1
        with:
          status: starting
          message: Starting Docker Build and Push...
          if: always()
      - run: |
          echo PR #${{ github.event.number }} has been merged
      - uses: actions/checkout@v2
      - name: Build a Docker image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/devops-final-project:${{ env.IMAGE_TAG }} . \

          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/devops-final-project:${{ env.IMAGE_TAG }} ${{ secrets.DOCKERHUB_USERNAME }}/devops-final-project:latest
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish docker image
        run: docker push --all-tags ${{ secrets.DOCKERHUB_USERNAME }}/devops-final-project
      - name: Context
        uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
      - name: Get Kubeconfig
        uses: okteto/actions/namespace@v1
        id: kubeconf-step
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
          namespace: ${{ secrets.OKTETO_NAMESPACE }}
      - name: Deploy and Wait
        uses: okteto/actions/deploy@v1
        with:
          namespace: ${{ secrets.OKTETO_NAMESPACE }}
          manifest: k8s.yml
          tag: ${{ secrets.DOCKERHUB_USERNAME }}/devops-final-project:${{ github.sha }}
          waitOn: deployment/devops-final-project
      - name: Sleep for 90 seconds
        run: sleep 90s
        shell: bash
      - name: Verify
        uses: srt32/uptime@master
        with:
          url-to-hit: https://devops-final-project-${{ secrets.OKTETO_NAMESPACE }}.cloud.okteto.net/course/1
          expected-statuses: "200"
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()
